// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pXk4wl2hyQmYOZXoWt9IM3_bXvwD0hQ',
    appId: '1:323725125811:web:9639dced8f392e2fd628c6',
    messagingSenderId: '323725125811',
    projectId: 'movieterrorauth',
    authDomain: 'movieterrorauth.firebaseapp.com',
    storageBucket: 'movieterrorauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLB1uBQc-jBRUoD8iqo5UbbapevescFs',
    appId: '1:323725125811:android:54ff282a7952357fd628c6',
    messagingSenderId: '323725125811',
    projectId: 'movieterrorauth',
    storageBucket: 'movieterrorauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdGxxcrcRL1fmEgJn6nqXSXWWoPLZ8d0',
    appId: '1:323725125811:ios:810b20e876f48117d628c6',
    messagingSenderId: '323725125811',
    projectId: 'movieterrorauth',
    storageBucket: 'movieterrorauth.appspot.com',
    iosBundleId: 'com.example.newMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdGxxcrcRL1fmEgJn6nqXSXWWoPLZ8d0',
    appId: '1:323725125811:ios:810b20e876f48117d628c6',
    messagingSenderId: '323725125811',
    projectId: 'movieterrorauth',
    storageBucket: 'movieterrorauth.appspot.com',
    iosBundleId: 'com.example.newMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0pXk4wl2hyQmYOZXoWt9IM3_bXvwD0hQ',
    appId: '1:323725125811:web:274092e2eb5bc6cad628c6',
    messagingSenderId: '323725125811',
    projectId: 'movieterrorauth',
    authDomain: 'movieterrorauth.firebaseapp.com',
    storageBucket: 'movieterrorauth.appspot.com',
  );
}
